# spring.application.name defines the name of the Spring Boot application
#
# This name is used:
# ? In Spring Boot logs
# ? In Spring Boot Actuator
# ? For identifying the application in microservices
#
# It does NOT affect functionality, only identification
spring.application.name=research-assistant



# gemini.api.url stores the Gemini API URL
#
# ${GEMINI_URL} means:
# This value is NOT hardcoded here
# It is read from Environment Variable named GEMINI_URL
#
# Example Environment Variable:
#
# GEMINI_URL=https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent
#
# Why use Environment Variable?
#
# ? Security
# ? Avoid exposing API URL in code
# ? Easy configuration change
#
gemini.api.url=${GEMINI_URL}



# gemini.api.key stores Gemini API Key
#
# ${GEMINI_KEY} means:
# Value is read from Environment Variable GEMINI_KEY
#
# Example:
#
# GEMINI_KEY=AIzaSyXXXXXXXXXXXX
#
# Why use Environment Variable?
#
# ? Protect secret key
# ? Prevent exposing in GitHub
# ? Follow security best practices
#
gemini.api.key=${GEMINI_KEY}